version: '3.3'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
    ports:
      - "lockalhost:lockahost"  #пробросить порты
  database:
    build:
      context: DB
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - "lockalhost:lockahost"
  listener:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    networks:
      - backend
networks:
  backend: